{
 "title": "IoT Sample Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Count of Events",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "iot",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "SensorData\r\n| where $__timeFilter(Timestamp)\r\n| summarize CountOfEvents = count()",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Events per Asset",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "database": "iot",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "SensorData\r\n| where $__timeFilter(Timestamp)\r\n| summarize measure_count=count() by AssetId",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Distribution per Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "database": "iot",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "SensorData\r\n| summarize event_count=count() by bin(Timestamp, 1d)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Average Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "database": "iot",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "SensorData\r\n| where $__timeFilter(Timestamp)\r\n| project Timestamp, Temperature\r\n| summarize avg(Temperature) by bin(Timestamp, 10s)",
     "querySource": "raw"
    }
   ]
  }
 ]
}